version: '3'
services:
  broker:
    build: broker
    
  auldfellas:
    build: auldfellas
    environment:
      HOST: broker
    depends_on:
      - broker
  dodgygeezers:
    build: dodgygeezers
    environment:
      HOST: broker
    depends_on:
      - broker
  girlsallowed:
    build: girlsallowed
    environment:
      HOST: broker
    depends_on:
      - broker
  client:
    build: client
    environment:
      HOST: broker
    depends_on:
      - broker
      - auldfellas
      - dodgygeezers
      - girlsallowed
